### ISSUE TITLE
AMD FSR 3.0 Causes shadowing/motion blur 

### ISSUE THREAD

**Issue by bilalzangetsu** [Lyall/FFXVIFix#1]
![ff16fix issue ](https://github.com/user-attachments/assets/4af2b82c-cf11-406a-92ff-d86140f97a38)

Issue with excessive motion blur / sillouette shadow

This issue occurs when any movement is made and is especially apprent when the camera is moved. This only occurs when AMD FSR 3.0 is enabled. I have not tried other upscaling methods within AMD FSR 3.0 but was utilising Native AA in this screenshot. Would also note that I was in teh 100+ FPS range so low FPS was not the issue here.

**Comment by Lyall** [comment]
I think I was able to fix it. Can you try this test build and confirm if it works on your end too?

[FFXVIFix_v0_7_2_test.zip](https://github.com/user-attachments/files/16701193/FFXVIFix_v0_7_2_test.zip)

**Comment by Charlaylay** [comment]
I just tested, no more ghosting problems for me either
(3440x1440p)

**Comment by bilalzangetsu** [comment]
Yes I can confirm that the Test build worked. My Res is 3440x1440p.

Thanks

**Comment by LittleTale** [comment]
Amazing work ! thanks

**Comment by LittleTale** [comment]
new update broke it. . .  Damn

**Comment by Lyall** [comment]
Should be fixed again in this build.

[FFXVIFix_v0.7.2_test2.zip](https://github.com/user-attachments/files/16729212/FFXVIFix_v0.7.2_test2.zip)

**Comment by Lyall** [comment]
Fixed in v0.7.2
