### ISSUE TITLE
Feature Suggestion: removing TAA and/or Depth of Field with FSR3+FG on

### ISSUE THREAD

**Issue by enderx30** [Lyall/FFXVIFix#10]
While FFXVI looks amazing with its lighting, the baked-in TAA muddies the entire picture.
DLSS swap can remove the TAA; I was hoping there would be some way to achieve the same thing but with FSR3.
It would also be nice to remove the forced depth of field as well.

**Comment by Lyall** [comment]
I've added an option to remove depth of field in v0.7.7
