### ISSUE TITLE
Constrain HUD to 16:9

### ISSUE THREAD

**Issue by fuzzbyte** [Lyall/FFXVIFix#12]
Thanks for your work on this.  In my testing on nvidia surround (5760x1080), things look great aside from my HUD being on opposite ends. Your README screenshot seems to constrain the HUD though. I double checked my .ini and all settings seemed on. Something I'm missing?

![image](https://github.com/user-attachments/assets/a0a78441-2f30-44ab-b797-e1a62e4bdcf8)

**Comment by fuzzbyte** [comment]
Log File Contents:

> [2024-08-28 18:56:28.340] [FFXVIFix] [info] ----------
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] FFXVIFix v0.7.3 loaded.
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] ----------
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Path to logfile: S:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XVI DEMO\FFXVIFix.log
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] ----------
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Module Name: ffxvi_demo.exe
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Module Path: S:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XVI DEMO\
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Module Address: 0x140000000
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Module Timestamp: 1724280390
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] ----------
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Path to config file: S:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XVI DEMO\FFXVIFix.ini
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] ----------
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: bFixResolution: true
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: bFixHUD: true
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: bFixFOV: true
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: fAdditionalFOV: 0
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: bUncapFPS: true
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: bCutsceneFramegen: true
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: iJXLThreads: 4
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] Config Parse: fJXLQuality: 99.5
> [2024-08-28 18:56:28.340] [FFXVIFix] [info] ----------
> [2024-08-28 18:56:28.346] [FFXVIFix] [info] Resolution Fix: Address is ffxvi_demo.exe+67c856
> [2024-08-28 18:56:28.346] [FFXVIFix] [info] Resolution Fix: Patched instruction.
> [2024-08-28 18:56:28.359] [FFXVIFix] [info] Current Resolution: Address is ffxvi_demo.exe+a88fe1
> [2024-08-28 18:56:28.368] [FFXVIFix] [info] FSR Framegen Aspect: Address is ffxvi_demo.exe+9894e6
> [2024-08-28 18:56:28.370] [FFXVIFix] [info] HUD Size: Address is ffxvi_demo.exe+20100b
> [2024-08-28 18:56:28.382] [FFXVIFix] [info] HUD Pillarboxing: Address is ffxvi_demo.exe+b80ae4
> [2024-08-28 18:56:28.391] [FFXVIFix] [info] Movies: Address is ffxvi_demo.exe+abd9b4
> [2024-08-28 18:56:28.394] [FFXVIFix] [info] Eikon Cursor: Address is ffxvi_demo.exe+2c23ca
> [2024-08-28 18:56:28.400] [FFXVIFix] [info] FOV: Address is ffxvi_demo.exe+587dfb
> [2024-08-28 18:56:28.406] [FFXVIFix] [info] Framerate Cap: Address is ffxvi_demo.exe+802133
> [2024-08-28 18:56:28.406] [FFXVIFix] [info] Framerate Cap: Patched instruction.
> [2024-08-28 18:56:28.410] [FFXVIFix] [info] Cutscene Frame Generation: Address is ffxvi_demo.exe+446684
> [2024-08-28 18:56:28.410] [FFXVIFix] [info] Cutscene Frame Generation: Patched instruction.
> [2024-08-28 18:56:28.410] [FFXVIFix] [info] JXL Tweaks: JxlEncoderDistanceFromQuality address = 7ffe118888d0
> [2024-08-28 18:56:28.410] [FFXVIFix] [info] JXL Tweaks: JxlThreadParallelRunnerDefaultNumWorkerThreads address = 7ffea9cd2080
> [2024-08-28 18:56:28.410] [FFXVIFix] [info] JXL Tweaks: Hooked functions.


Screenshot of folder:
![image](https://github.com/user-attachments/assets/870e685a-32ed-443a-9066-4b6d56ce3c04)

**Comment by Lyall** [comment]
No there's no constrained 16:9 HUD option yet. The screenshot in the README is from the start of the game before the proper gameplay UI shows up. I do want to look into adding a 16:9 HUD option but it'll take time.

**Comment by Lyall** [comment]
Can you try out this test build? I've added the option to resize the gameplay HUD to various different sizes.

[FFXVIFix_v0.7.4_test.zip](https://github.com/user-attachments/files/16791297/FFXVIFix_v0.7.4_test.zip)

**Comment by fuzzbyte** [comment]
Loading up a few saves at different points, that shows the standard HUD looks good, and enemy indictors in combat still render well.

![image](https://github.com/user-attachments/assets/b2e0adff-5e6b-4aea-ae1a-3b8f53247e0c)

![image](https://github.com/user-attachments/assets/f9183a29-1659-4d97-8cbb-e5621ca0e941)

**Comment by fuzzbyte** [comment]
Dialog subtitles and quest markers look great, too. Bravo!
![Untitled](https://github.com/user-attachments/assets/78b93934-8566-4622-b296-1893a0843964)

**Comment by fuzzbyte** [comment]
Loot/experience pane also good.
![Untitled](https://github.com/user-attachments/assets/7d3a86a3-776d-4a0e-b2f2-35ef5e3d553f)

**Comment by Lyall** [comment]
Thank you for the detailed feedback! Looks like it's working well enough. I got some feedback elsewhere about an issue with the cursor during the last eikon fight which I have fixed in the next build. There's also an issue of strong vignetting in certain cutscenes that becomes noticeable >21:9.

**Comment by fuzzbyte** [comment]
All makes sense. Feel free to close this issue. I can open up new ones if I find any additional issues to report, though I probably won't touch the demo much more since I'm done with it and will wait for the main game. If you do need someone to quickly test something on a resolution like mine though, feel free to ping me.

**Comment by Lyall** [comment]
Alright, vignetting fixed and the eikon cursor issue is also fixed. v0.7.4 now includes the HUD size option.
