### ISSUE TITLE
Feature request: Set desired FPS Limit for cut scences

### ISSUE THREAD

**Issue by damedameningen** [Lyall/FFXVIFix#13]
Basically what the title sais.
Is it possible to add an option to limit the framrate to 60fps for example?
On my Rig I mostly get between 75-100Fps  during the scenes, so I tought it would be nice if its possible to lock the scences to a desired framrate.

If that is not possible then nevermind. Thank you anyway for your outstanding work

**Comment by AL2009man** [comment]
part of the list of feature request: https://github.com/Lyall/FFXVIFix/issues/6#issuecomment-2308559316

**Comment by Lyall** [comment]
Added in v0.7.7
