### ISSUE TITLE
Request version compatible with Reloaded II

### ISSUE THREAD

**Issue by amnjcl** [Lyall/FFXVIFix#151]
Hi Lyall, thanks again for this great mod. 
I’ve been hearing some reports of people having issues when trying to use FFXVIFix along with other mods that are run via Reloaded II. The only workaround seems to be to disable FFXVIFix in order to use a Reloaded II mod. 

Is there any chance that you might have some time to create a version of FFXVIFix that’s compatible with Reloaded?

Thanks in advance!

**Comment by WoooJenkies** [comment]
Wouldn't work, FFXVIFix isn't a .diff mod which Reloaded II is for.

**Comment by Nenkai** [comment]
> Wouldn't work, FFXVIFix isn't a .diff mod which Reloaded II is for.

Incorrect, this is specifically for the mod loader for FFXVI.
Reloaded supports native mods like these and it [has already been done here](https://github.com/Lyall/P3RFix/pull/39)

Unfortunately it seems the author has already moved on from this game and doesn't have an interest, seeing how many issues are open.

**Comment by WoooJenkies** [comment]
FFXVIfix is injected via a .dll file in the root of the game's folder (dinput8.dll), I was under the impression that RII would only work on FFXVI through 007.diff.pac, as it isn't the same as P3R.

**Comment by Nenkai** [comment]
Nah, packs don't play any part here.
Reloaded can deploy `.asi/.dll` files like this mod aswell.

There's some incompatibility going on somewhere for some people as this isn't the first time i've seen this. Ideally this should be built as a package reloaded (for better mod management, too).

**Comment by Sewer56** [comment]
Should I buy the game and investigate myself?

Although I'd prefer to not give publishers who used Denuvo money, I could do it if it really comes down to it in the worst case scenario.

In any case, what could possibly be the problem; does anyone have any specific ideas? There have been cases in the past where some mods used Silent's hooking code and that needed a patch due to a bug. I submitted PR myself and that was fixed a while back.

I believe in this case, if you're loading both FFXVIFix and Reloaded via ASI Loader then Reloaded would load second. I don't recall if same thing happens when starting via Reloaded, since I don't remember if DLLs are preloaded in suspended processes.

Do you still get the Reloaded console in any case?

**Comment by Lyall** [comment]
I've added a Reloaded-II package starting with v0.8.5. It seemed to work fine in my (limited) testing.

**Comment by Sewer56** [comment]
I'm still curious why it reportedly wouldn't work for them in the first place; I'm not aware with any interop bugs with safetyhook, ASI Loader or the like. An end user should expect stuff to 'just work', regardless of what they did; so I'm more curious from that end.

**Comment by Lyall** [comment]
> I'm still curious why it reportedly wouldn't work for them in the first place; I'm not aware with any interop bugs with safetyhook, ASI Loader or the like. An end user should expect stuff to 'just work', regardless of what they did; so I'm more curious from that end.

I've just tried the last version (v0.8.4) of FFXVIFix installed locally, then running Reloaded-II along with the FF16 mod loader and a mod. It seems to work fine on my end.

![ffxvi_2024_10_20_15_25_44_247](https://github.com/user-attachments/assets/722db4c2-8070-4cc8-8953-04c631efa780)

**Comment by Sewer56** [comment]
Yeah, I'd expect it to run just fine too, that's the odd part.

**Comment by Lyall** [comment]
Does the issue maybe stem from the deploying of the ASI loader? If I clear out FFXVIFix and the bundled ASI loader I include, then add some mods in Reloaded-II and hit deploy ASI loader, it only seems to deploy the bootstrapper ASI file.

**Comment by Sewer56** [comment]
I use a heuristic that works by checking for an existing `.asi` file in the `scripts`, `plugins` or `base game folder`. If one exists, an assumption is made that an `.asi` loader is already installed; in which case Reloaded will only drop the bootstrapper into the game folder; and no loader.

If they install standalone FFXVIFix, or similar and then deploy ASI Loader from Reloaded; a second ASI Loader should not be installed.

**Comment by Lyall** [comment]
> I use a heuristic that works by checking for an existing `.asi` file in the `scripts`, `plugins` or `base game folder`. If one exists, an assumption is made that an `.asi` loader is already installed; in which case Reloaded will only drop the bootstrapper into the game folder; and no loader.
> 
> If they install standalone FFXVIFix, or similar and then deploy ASI Loader from Reloaded; a second ASI Loader should not be installed.

That makes a lot of sense. I just verified game files, wiped Reloaded-II app data and tried again. This time it deployed correctly so I must have missed something when clearing files out of the game folder. 

![image](https://github.com/user-attachments/assets/3ff58ac6-c182-41f7-9fce-96fba68e4c08)

Apologies for this little tangent, total user error on my part.
