### ISSUE TITLE
TEST on Full Game Release

### ISSUE THREAD

**Issue by LittleTale** [Lyall/FFXVIFix#17]
30FPS Lock removal seems to work fine, but the main game ignore the ultrawide patch, both in gameplay and cut-scene.

Also lazy SE forget to remove "buy from steam page" option in the menu ! XD

**Comment by KellRL** [comment]
Can confirm all of that. Waiting for the update of this fix to play on 21:9 <3

**Comment by GosuDRM** [comment]
Lyall we need you

**Comment by nlikeflynn** [comment]
That’s so cool that the 30fps cap removal still works. At work so can’t play till tonight haha. I bet Lyall will have it fixed soon!

**Comment by IronSlasher** [comment]
"Also lazy SE forget to remove "buy from steam page" option in the menu ! XD"

Haha noticed that too.

**Comment by Alexsnow5** [comment]
Please Lyall you're our god and saver right now, praised be thy name. Jokes aside thanks for your hard work good sir.

**Comment by Lyall** [comment]
Give [v0.7.5](https://github.com/Lyall/FFXVIFix/releases) a try.

**Comment by KellRL** [comment]
> Give [v0.7.5](https://github.com/Lyall/FFXVIFix/releases) a try.

It works! Thank you so much <3

**Comment by goopsauce** [comment]
Thank you so much!

**Comment by Alexsnow5** [comment]
Thank you Lyall!

**Comment by IronSlasher** [comment]
You are the KING!!!! thanks soooo much, the letter boxing made me want to vomit! Especially after seeing the Demo in full 21:9 glory!

**Comment by LittleTale** [comment]
I can't believe you got it fixed so fast ! Genius

**Comment by Abelfei** [comment]
Can someone help me?  Idk what I am doing wrong, I have never had any problems with mods like in the past.  I extratced into the said ghame folder, go into config file and leave everything except change hud to 4 for 21:9.  I should leave everything at true right?  Game is the same eveytime I boot.

**Comment by Abelfei** [comment]
NVm got it

**Comment by tjgoblue** [comment]
> NVm got it

how did you fix it? I launch the game and still have black bars

**Comment by Alexsnow5** [comment]
> Can someone help me? Idk what I am doing wrong, I have never had any problems with mods like in the past. I extratced into the said ghame folder, go into config file and leave everything except change hud to 4 for 21:9. I should leave everything at true right? Game is the same eveytime I boot.

Did you download the last version v0.7.5?

**Comment by Abelfei** [comment]
> > NVm got it
> 
> how did you fix it? I launch the game and still have black bars

Either did option 0 for HUD or started game from folder made it work.
