### ISSUE TITLE
I just can't play without 21:9... not anymore!! Please can you update the fix?, promise ill buy (donate) more than a coffee!

### ISSUE THREAD

**Issue by unstat1c** [Lyall/FFXVIFix#18]
I just can't play without 21:9... not anymore!! Please can you update the fix?, promise ill buy (donate) more than a coffee!

**Comment by Lyall** [comment]
You don't need to promise anything haha. I'll get the fix updated once my game is downloaded. It's going to take a bit so I would expect to see an update tomorrow.

**Comment by goopsauce** [comment]
Can I let you borrow my internet to help? Haha

**Comment by unstat1c** [comment]
> You don't need to promise anything haha. I'll get the fix updated once my game is downloaded. It's going to take a bit so I would expect to see an update tomorrow.

sorry but i insist! ppl who spend time helping others should be reward time to time.

**Comment by Lyall** [comment]
Give [v0.7.5](https://github.com/Lyall/FFXVIFix/releases) a try. Should work on the full game for now until I can get the game installed and look at it closer.

**Comment by balahadya** [comment]
Works 100% thank you so much!

**Comment by KellRL** [comment]
> Give [v0.7.5](https://github.com/Lyall/FFXVIFix/releases) a try. Should work on the full game for now until I can get the game installed and look at it closer.

Thank you so much! It was so fast from the very release of the game to help all people get the max of the game! <3

**Comment by IamGrug** [comment]
ty dev
