### ISSUE TITLE
Artifacts on Full Game + DOF cropped 

### ISSUE THREAD

**Issue by LittleTale** [Lyall/FFXVIFix#19]
CPU: 7800X3D
GPU: 7900XTX
RAM: 64GB DDR5 6000Mhz
Resolution: 3440x1440 @175Hrz (Game locked at 87.5FPS with in-game lock)

1- Seems to still have the FSR 3.1 ghosting when using the ultrawide patch with FSR3.1 on quality and Frame Gen ON.
tried other FSR settings, doesnt seem to correct itself, it only appears when using FSR Frame Generation. (see 1.)

2- seems like the in-engine cut-scenes DOF doesn't take into account the ultrawide, DOF apply to the whole side of the image. (see 2.)

1
![Screenshot (10)](https://github.com/user-attachments/assets/6a53672c-e4de-45f5-9379-3dc9a00b5fb9)
![Screenshot (9)](https://github.com/user-attachments/assets/a8d33b38-39ca-4196-b49c-ee73f5b37e1e)

2
![20240917132344_1](https://github.com/user-attachments/assets/4573722d-4bf3-496f-aa0a-872ebbe0accd)

**Comment by FakeGiraffe93** [comment]
do you know if this happened on 0.7.4 on the demo using FSR FG?

**Comment by LittleTale** [comment]
already deleted the DEMO... can't check until tonight.

**Comment by Lyall** [comment]
For the FSR ghosting, are you using motion blur? Part of what FFXVI fix does is enabling the use of motion blur with frame generation (although I don't advise it). I can only replicate a small amount of ghosting on my end with FSR frame generation and it looks similar to the slight ghosting with DLSS frame gen. 

Can you post your `FFXVIFix.log` file to see if the FSR framegen aspect ratio fix is being applied? It will ghost badly without this fix.

As for DOF, I can't replicate that issue. Are you using photo mode to get these shots? There is a blurring pillarbox effect when in photomode that I plan on trying to resolve in the future. 

![ffxvi_2024_09_17_22_22_57_290](https://github.com/user-attachments/assets/5791cc5e-7ba5-4265-ab24-0ac883bdd0b8)

**Comment by LittleTale** [comment]
Thanks a lot for the quick response. Here is the log.
also you were right, the DOF is only when inside photo mode ! sorry 🙏 😅

[FFXVIFix.log](https://github.com/user-attachments/files/17035313/FFXVIFix.log)

**Comment by Abelfei** [comment]
I couldn't get it to work until one of two things I did differently
1:  Instead of option 4 for 21:9 on HUD, I did option 1 for automatic.
2.  I launched the game from the folder, not Steam.

**Comment by Lyall** [comment]
> Thanks a lot for the quick response. Here is the log. also you were right, the DOF is only when inside photo mode ! sorry 🙏 😅

I'll hopefully be able to address the photo mode stuff soon. 

> also unrelated, do you know a fix for monitor sleep ? I have a OLED monitor so the "turn off screen" timer is set to 5 minutes, normally in-game it never goes to sleep, but for unknows reason windows doesn't seems to detect FFXVI as a game, and when watching a cut-scene my monitor goes black after 5 min if i don't press any input ! 😅

For that, if I'm remembering correctly, you could use SpecialK. I think it has a feature to keep monitors awake when playing a game but I could be wrong. There's a boat load of features so it's hard to keep track. 

> [FFXVIFix.log](https://github.com/user-attachments/files/17035313/FFXVIFix.log)

Your log looks good. The FSR framegen fix is in the right place so I suspect it is working okay. The ghosting would be _extremely_ bad without it.

**Comment by LittleTale** [comment]
Yeah, so your fix seems to work, it looks like the FSR3.1 FrameGen won't stop ghosting with motion blur enabled. I'll just play with it OFF, can live with that ! 😅

thanks a lot for all the amazing work you do for the community and all those games that you spend your time fixing !

**Comment by Lyall** [comment]
> Yeah, so your fix seems to work, it looks like the FSR3.1 FrameGen won't stop ghosting with motion blur enabled. I'll just play with it OFF, can live with that ! 😅
> 
> thanks a lot for all the amazing work you do for the community and all those games that you spend your time fixing !

I'll make the motion blur + frame gen option disabled by default in the next version. It looks okay-ish with DLSS frame gen but it's probably better as an opt-in setting so people don't end up with poor image quality. 

And no problem, I'm glad the fix is useful for you and so many other people, it's been very nice seeing people's feedback!

**Comment by Lyall** [comment]
Oh wow, cool seeing your input Frans. Really appreciate the work you've done with all your camera tools and UUU!

There is some HUD pillarboxing that I've already fixed in other menus, though this doesn't appear to apply in photo mode.

```
ffxvi.exe+BF192C - C5FA102D 34 EDA500    - vmovss xmm5,[ffxvi.exe+1650668]
```

I don't know if it's worth investigating from there too, but I'll look in to that.

**Comment by FransBouma** [comment]
> Oh wow, cool seeing your input Frans. Really appreciate the work you've done with all your camera tools and UUU!
> 
> There is some HUD pillarboxing that I've already fixed in other menus, though this doesn't appear to apply in photo mode.
> 
> ```
> ffxvi.exe+BF192C - C5FA102D 34 EDA500    - vmovss xmm5,[ffxvi.exe+1650668]
> ```
> 
> I don't know if it's worth investigating from there too, but I'll look in to that.

Will look into that as well.

**Comment by FransBouma** [comment]
```
ffxvi.exe+C23B0B - C5F81140 20           - vmovups [rax+20],xmm0
ffxvi.exe+C23B10 - E8 377AFEFF           - call ffxvi.exe+C0B54C
ffxvi.exe+C23B15 - C5FA1044 24 20        - vmovss xmm0,[rsp+20]         << Replace with xorps xmm0, xmm0 
ffxvi.exe+C23B1B - 8B 8B 1C020000        - mov ecx,[rbx+0000021C]
ffxvi.exe+C23B21 - 41 BA 81808080        - mov r10d,80808081 { (0) }
```
That gets rid of it, sadly also parts of the pm menu. 
But it's close!

**Comment by Lyall** [comment]
```cpp
        // Photo mode blur background 
        uint8_t* PhotoModeBackgroundScanResult = Memory::PatternScan(baseModule, "C4 ?? ?? ?? ?? ?? C5 ?? ?? ?? C5 ?? ?? ?? C5 ?? ?? ?? C5 ?? ?? ?? 48 8D ?? ?? ?? 49 ?? ??");
        if (PhotoModeBackgroundScanResult) {
            spdlog::info("Photo Mode Background: Address is {:s}+{:x}", sExeName.c_str(), (uintptr_t)PhotoModeBackgroundScanResult - (uintptr_t)baseModule);

            static SafetyHookMid PhotoModeBackgroundMidHook{};
            PhotoModeBackgroundMidHook = safetyhook::create_mid(PhotoModeBackgroundScanResult,
                [](SafetyHookContext& ctx) {
                    if (ctx.r9 + 0xD0) {
                        uintptr_t hudElementAddr = *(uintptr_t*)(ctx.r9 + 0xD0);
                        if (hudElementAddr) {
                            char* sElementName = (char*)hudElementAddr + 0x40;
                            if (strcmp(sElementName, "bg_blur_l") == 0 && *reinterpret_cast<int*>(ctx.r9 + 0x40) == 1920)
                            {
                                spdlog::info("Fixed background blur");
                                *reinterpret_cast<int*>(ctx.r9 + 0x40) = 0;
                            }
                        }
                    }
                });
        }
        else if (!PhotoModeBackgroundScanResult) {
            spdlog::error("Photo Mode Background: Pattern scan failed.");
        }
```

This seems to work as a somewhat hacky solution. Though I'm sure there's probably a better way of sorting it.

The blurred portion doesn't seem to change size by the way, if you play at 32:9 or even wider it remains the same.

![ffxvi_2024_09_18_20_16_21_029](https://github.com/user-attachments/assets/98184b98-e8eb-4980-bd57-6d9ab340d32f)

![ffxvi_2024_09_18_20_16_03_871](https://github.com/user-attachments/assets/b667a185-e307-42d6-9ea7-4770f1eb97f9)

**Comment by FransBouma** [comment]
Nice! I traced the call paths but it's indeed super generic code that's not really separable for this particular element. The 1920 value is read from a temp memory page but where the value is coming from is unknown...  

```
ffxvi.exe+C2C5FE - 48 8B CF              - mov rcx,rdi
ffxvi.exe+C2C601 - 8B 53 08              - mov edx,[rbx+08]
ffxvi.exe+C2C604 - E8 9F90FFFF           - call ffxvi.exe+C256A8
ffxvi.exe+C2C609 - 8B 53 44              - mov edx,[rbx+44]        << READ the 1920 from the temp page
ffxvi.exe+C2C60C - 44 8B 43 48           - mov r8d,[rbx+48]
ffxvi.exe+C2C610 - E8 C390FFFF           - call ffxvi.exe+C256D8   << Write it onto the stack which is then later on ending up in the block that's used for the UI
ffxvi.exe+C2C615 - 8B 43 24              - mov eax,[rbx+24]
ffxvi.exe+C2C618 - 44 8D 66 01           - lea r12d,[rsi+01]
```

**Comment by Lyall** [comment]
I've also tried tracking things back further. 
```
ffxvi.exe+C2972C - 48 83 EC 28           - sub rsp,28 { 40 }
ffxvi.exe+C29730 - 83 BA 18020000 07     - cmp dword ptr [rdx+00000218],07 { 7 }
ffxvi.exe+C29737 - 4C 8B CA              - mov r9,rdx
>> ffxvi.exe+C2973A - 48 8B 41 40           - mov rax,[rcx+40]
ffxvi.exe+C2973E - 48 89 44 24 30        - mov [rsp+30],rax
```

If you check what addresses are accessed on this line, the two results for 660 are the individual sides of the background blur. If you dissect structure in Cheat Engine and look at the same pointer of 0xD0 for the name, then they are label `bg_blur#1` and `bg_blur`. The even have some positioning data at [rcx+B0]. 

![image](https://github.com/user-attachments/assets/1624fb0a-ed4f-405f-b280-b6c574458d78)

These positioning values, along with the blur being a specific size might make it unique enough to compare on that instead of a UI element name.

**Comment by FransBouma** [comment]
The 660 values, are they coming from a source that's traceable? Sounds like setting those source values to 0 fixes it. But it's likely the same maze as where I ended up in with my traces... :( 

Good job tho! 👍

**Comment by Lyall** [comment]
> The 660 values, are they coming from a source that's traceable? Sounds like setting those source values to 0 fixes it. But it's likely the same maze as where I ended up in with my traces... :(
> 
> Good job tho! 👍 A conditional breakpoint in CE might help (e.g. check that the destination register contains the address of the 660 value ( -0x40) when you break on the write for that value)

This is as far back as I can trace it to:
```
ffxvi.exe+C2C601 - 8B 53 08              - mov edx,[rbx+08]
ffxvi.exe+C2C604 - E8 9F90FFFF           - call ffxvi.exe+C256A8
>> ffxvi.exe+C2C609 - 8B 53 44              - mov edx,[rbx+44]
ffxvi.exe+C2C60C - 44 8B 43 48           - mov r8d,[rbx+48]
ffxvi.exe+C2C610 - E8 C390FFFF           - call ffxvi.exe+C256D8
ffxvi.exe+C2C615 - 8B 43 24              - mov eax,[rbx+24]

Seems to be loaded in there. When I change it to 0, it's written back to 660 when loading photo mode but I can't track what's writing to it.

**Comment by FransBouma** [comment]
register shenanigans, might be denuvo's tricks. 
The value might indeed be written/read from temporary blocks, which is quite tedious. :(

**Comment by Lyall** [comment]
I think the best I can get is this [bf94106.](https://github.com/Lyall/FFXVIFix/commit/bf94106cd396bbd660e6437c69ae4c737bb3dd96)

There's 3 checks at least, and now no dereferencing of pointers and strcmp. I would assume a false positive is very unlikely.

**Comment by Lyall** [comment]
Added a fix for the blurry pillarboxing in v0.7.7

**Comment by Lyall** [comment]
> keep in mind that comparing a float with a constant might fail even tho the float looks the same. So you might want to compare with a >= constant - epsilon and a <= constant + epsilon instead of a ==constant. But other than that... yeah these things sometimes suck... :(

Something like this?
```cpp
if (ctx.rcx + 0x40) {
    // Check size, should be 660x1080
    if ((*reinterpret_cast<int*>(ctx.rcx + 0x40) >= 655 && *reinterpret_cast<int*>(ctx.rcx + 0x40) <= 665) && (*reinterpret_cast<int*>(ctx.rcx + 0x44) >= 1075 && *reinterpret_cast<int*>(ctx.rcx + 0x44) <= 1085)) {
        // Check horizontal position
        if ((*reinterpret_cast<float*>(ctx.rcx + 0xB0) >= -675.00f && *reinterpret_cast<float*>(ctx.rcx + 0xB0) <= -665.00f) || (*reinterpret_cast<float*>(ctx.rcx + 0xB0) >= 1925.00f && *reinterpret_cast<float*>(ctx.rcx + 0xB0) <= 1935.00f)) {
            // Write 0 to width
            *reinterpret_cast<int*>(ctx.rcx + 0x40) = 0;
        }
    }
}
```

**Comment by FransBouma** [comment]
yeah something like that, that's because floats aren't precise, sadly...

**Comment by Lyall** [comment]
I've added that extra change to v0.7.8. I think with that this issue is probably worth closing. It would be nice if there was a neater way of fixing it but I think this isn't too bad (I've done a lot worse before 😓). Thanks again for the help and sharing info @FransBouma
