### ISSUE TITLE
Cutscene still stuck at 30 fps

### ISSUE THREAD

**Issue by Walbangerbw** [Lyall/FFXVIFix#22]
Hello, was just looking for sometype of help with this? I followed the instructions extracted the download to the game folder and nothing seems to have changed, i have a fps counter and it seems that the cutscenes stay at 30. is there anything else i need to do? is it only the one download? thank you

**Comment by Lyall** [comment]
Can you post your `FFXVIFix.log` file please? If you do not have on then please post a screenshot of the game folder so we can make sure the fix is installed correctly.

**Comment by Kurloss** [comment]
I'm also still getting 30 fps in cutscenes. Have attached the 2 files requested. Hopefully this helps.
[FFXVIFix.log](https://github.com/user-attachments/files/17036483/FFXVIFix.log)
![image](https://github.com/user-attachments/assets/51310b0e-f003-48dc-a291-6fcf325b21b6)

**Comment by Lyall** [comment]
> I'm also still getting 30 fps in cutscenes. Have attached the 2 files requested. Hopefully this helps. [FFXVIFix.log](https://github.com/user-attachments/files/17036483/FFXVIFix.log)

Your log looks good and you've got the mod installed correctly. Are you getting 30fps in every cutscene or just some of them? There are several near the start of the game that are pre-rendered and can't run at higher than 30fps.

**Comment by Walbangerbw** [comment]
sorry i just got home from work, I actually got it to work i just redownloaded everything fresh and for some reason this time it worked? thanks again tho!

**Comment by Kurloss** [comment]
Also seems to be working for me. Must have just been the early pre-rendered cutscenes.
