### ISSUE TITLE
Mod not working (demo)

### ISSUE THREAD

**Issue by epicsarrow** [Lyall/FFXVIFix#23]
Wanted to test this on the demo before buying the full game but I can't get the mod to work, I made sure all the files are inside the installation folder. This is my log file
[FFXVIFix.log](https://github.com/user-attachments/files/17035171/FFXVIFix.log)

**Comment by Lyall** [comment]
Demo compatibility is removed for now in v0.7.5. You'll have to go back to v0.7.4 or older with the demo.

**Comment by epicsarrow** [comment]
No problem, thanks for responding
