### ISSUE TITLE
Windows cannot find unable to load game.

### ISSUE THREAD

**Issue by ResuTheRunning** [Lyall/FFXVIFix#24]
I'm having an error with the steam version.  I put the command in and it sends back an error.  Windows cannot find WINEDLLOVERRIDE="dinput8=n,b".  I maybe just stupid from being sick but can't figure out for the life of me what is wrong.

**Comment by Lyall** [comment]
You don't need to use that launch command on windows. It's only for Linux/Steam Deck. If you remove it and try to launch the game, it should work.

**Comment by ResuTheRunning** [comment]
That was it.  Too sick for brain to work right.  Thank you.  Me are not paying attention big dumb. XD
