### ISSUE TITLE
Cutscene still stuck at 30 fps [2]

### ISSUE THREAD

**Issue by nykosx** [Lyall/FFXVIFix#25]
first time loading game had an error (think it was 255), after that tried reloading the game and no error pop up.

![image](https://github.com/user-attachments/assets/610f8f94-1e03-47e5-8898-18489a6749b7)
![image](https://github.com/user-attachments/assets/3ea6870f-df99-4641-85e6-4be42e5a6780)

**Comment by Lyall** [comment]
I'm not seeing `FFXVIFix.asi`, only `FFXVIFix.ini` and `dinput8.dll`. Can you redownload the fix and extract it again?

**Comment by nykosx** [comment]
Done, got this error when loading the game

![image](https://github.com/user-attachments/assets/b094eecb-539d-44eb-a842-13dc848ccd47)

after this error, the FFXVIFix.asi got deleted.

tried again disabling windows defender and it worked, tho i can't re-enable

**Comment by Lyall** [comment]
> Done, got this error when loading the game
> 
> ![image](https://private-user-images.githubusercontent.com/181904556/368365369-b094eecb-539d-44eb-a842-13dc848ccd47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTM1MDMsIm5iZiI6MTcyNjYxMzIwMywicGF0aCI6Ii8xODE5MDQ1NTYvMzY4MzY1MzY5LWIwOTRlZWNiLTUzOWQtNDRlYi1hODQyLTEzZGM4NDhjY2Q0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QyMjQ2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmY5MjY2MmZkOWEzNDE0OWYyOGU0YjczN2RhYWJhYWIyN2Y4ODFhYTRkOWUzMmMyY2M3MzQ4YjkzNjE2YmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b0u83BydBsXhZfdYfQNvX8SXopH90DmT6HXdVk9l1ug)
> 
> after this error, the FFXVIFix.asi got deleted.
> 
> tried again disabling windows defender and it worked, tho i can't re-enable or the the issue persists

Ah it's probably getting falsely flagged by Windows Defender. Is it coming up detected as Wacatac or something? I've had defender pop up literally 2 seconds after hitting "Build" sometimes. It loves to generate false positives. You'll have to allow it on your machine through defender, or just wait for the flag to disappear. Alternatively it might go away in a new version of FFXVIFix.

**Comment by nykosx** [comment]
Yep, this seems to be it.

**Trojan:Win32/Wacatac.B!ml**

Thanks for the help

**Comment by Lyall** [comment]
Yeah that's the generic name Windows Defender applies to anything that looks ever so slightly suspicious. You should be safe to just allow it through Windows Defender. If you've got any worries, the source code is all here and the builds are compiled on GitHub runners!
