### ISSUE TITLE
Feature request: Shift FOV center over so Clive stops being off-center

### ISSUE THREAD

**Issue by amnjcl** [Lyall/FFXVIFix#26]
First, thanks so much for the work you’ve done! 

I noticed that when I widen the FOV, the fact that Clive is off-center becomes significantly more noticeable and it’s kind of frustrating to deal with. 

Is it at all possible to adjust the position of the camera to shift over so that Clive stops being off center? If that could be added as a feature that would be great!

**Comment by Lyall** [comment]
Added in v0.7.7
