### ISSUE TITLE
Similar fix for other games?

### ISSUE THREAD

**Issue by SynStark** [Lyall/FFXVIFix#28]
Hello, I apologize for making the post here, I just couldn't find any other way to reach you.

I've used 2 of your Fixes now for my 16:10 screen for Wukong and FF16 and both work great. 
I wanted to ask is it possible to make the same one for Elden Ring? It's a pain in the ass playing ER in 16:10 because I have to disable a bunch of stuff and play offline which is locking me out of a lot of online features, so I wanted to ask if it's possible to create a 16:10 fix for ER which would allow online play?

Thank you again for all the work you do!

**Comment by Lyall** [comment]
There's no way I know of for bypassing EAC in Elden Ring while maintaining online play. Bypassing anti-cheat is not an area I'm very familiar with. Unfortunately in this case and with other games that have anti-cheat, we're at the mercy of the developers when it comes to supporting things like ultrawide or 16:10 displays.

Sorry I can't be of more help!

**Comment by SynStark** [comment]
> There's no way I know of for bypassing EAC in Elden Ring while maintaining online play. Bypassing anti-cheat is not an area I'm very familiar with. Unfortunately in this case and with other games that have anti-cheat, we're at the mercy of the developers when it comes to supporting things like ultrawide or 16:10 displays.
> 
> Sorry I can't be of more help!

Got it, thank you for the response!
Have a great day!
