### ISSUE TITLE
Eikon battle in ultrawide

### ISSUE THREAD

**Issue by LittleTale** [Lyall/FFXVIFix#3]
When you controll Pheanix in the castle assault toward the end of the demo and you have to manually aim at Ifirt, the aim reticle is off probably because of the ultrawide fix, you actually need to aim around 5CM left of ifrit to have the reticule confirm that you are on target (it changes from a cross to a circle)

playing at 3440x1440.

**Comment by Lyall** [comment]
This is a known issue. I've yet to get to that point of the game so I haven't had a chance to try and fix it yet. Once I get there and have more information, I'll come back and update this issue.

**Comment by LittleTale** [comment]
Thank you so much for all your dedication and work to get that fix up so fast !
Random question, do you recognize the engine the game is running on ? Is it a SE engine from another game heavily modified or a new one entirely ?

**Comment by mihir-io** [comment]
If it's not possible to fix the offset at ultra wide resolutions, it would be great if there was a way to have it revert to 16:9 for those battles -- either automatically or via a hotkey.

At 32:9, the offset becomes way too large to try and work around, and unfortunately the pause menu doesn't have the option for switching resolutions during the fight.

**Comment by LittleTale** [comment]
> If it's not possible to fix the offset at ultra wide resolutions, it would be great if there was a way to have it revert to 16:9 for those battles -- either automatically or via a hotkey.
> 
> At 32:9, the offset becomes way too large to try and work around, and unfortunately the pause menu doesn't have the option for switching resolutions during the fight.


From what a friend tell me about the PS5 version. All other fight are more like QTE and less shooting, that's only when controlling the phoenix in the beginning. So hopefully it won't be needed . . .

**Comment by Lyall** [comment]
Fixed in v0.7.3
