### ISSUE TITLE
The mouse is not locked in screen

### ISSUE THREAD

**Issue by klownk** [Lyall/FFXVIFix#35]
If you use the windowed full screen to have ultra-wide, the mouse is no longer locked on the screen and get out in other monitors.
It's unplayable, especially in combat.

**Comment by Drahsid** [comment]
This is a vanilla issue with borderless mode. Set the game to fullscreen to fix it.

**Comment by klownk** [comment]
I tried that. If I set the game to fullscreen, I don't have ultrawide anymore.
