### ISSUE TITLE
When Fix Resolution is turned off on 32:9 monitor, in game image becomes 8:9.

### ISSUE THREAD

**Issue by Nezacant** [Lyall/FFXVIFix#37]
If trying to use the mod to just uncap cutscene frame rate but keep the 16:9 aspect ratio on a 32:9 monitor, turning off the fix resolution option, breaks the game resolution. What should become a 16:9 image becomes 8:9, aligned left of center.  See image link:
https://i.imgur.com/HH5k6r9.jpg
Aspect ratio becomes normal in a cutscene but returns to 8:9 in engine.

**Comment by Lyall** [comment]
Can you post your `FFXVIFix.log` file please?

**Comment by Nezacant** [comment]
[FFXVIFix.log](https://github.com/user-attachments/files/17057520/FFXVIFix.log)

**Comment by Lyall** [comment]
So you're trying to play at 2560x1440? Are you using borderless/fullscreen or windowed?

**Comment by Nezacant** [comment]
Correct. It happens in both full screen and borderless. Haven't tried windowed.

**Comment by Nezacant** [comment]
Should also mention that the pause menu shows up correctly.

**Comment by Lyall** [comment]
If you turn off the "Fix HUD" option in `FFXVIFix.ini`, does the same issue still happen?

**Comment by Nezacant** [comment]
Yes. Setting Fix HUD to 0 the issue persists.

**Comment by Nezacant** [comment]
That fixed it! Setting Fix HUD to false did the trick.
