### ISSUE TITLE
Suggestion to make camera centered

### ISSUE THREAD

**Issue by Celto107** [Lyall/FFXVIFix#38]
Would you be able to add an option that switches the camera so that its centered so that Clive is always in the middle? Sort of like Elden Ring/Soulsgames/etc that way there is no more shoulder/action camera

**Comment by Lyall** [comment]
I literally just added it! It's in v0.7.7

**Comment by Celto107** [comment]
> I literally just added it! You must have been reading my mind. It's available in v0.7.7

haha THANK YOU SO MUCH :)
