### ISSUE TITLE
Framegen disables itself on cutscenes. 

### ISSUE THREAD

**Issue by Toru77** [Lyall/FFXVIFix#4]
Cutscenes disable framegen which causes smoothness difference between gameplay and cutscenes.

**Comment by Lyall** [comment]
Are you positive that framegen is being disabled? I just did a quick test with the intro cutscene and the framerate takes a big leap with framegen on. I believe what you are seeing is the more demanding nature of the cutscenes. I'm fairly sure they are engaging a much higher quality depth of field and likely some other graphical improvements. They are very heavy even on something as high-end as a 4090.

Framegen off:
![ffxvi_demo_2024_08_22_20_12_44_346](https://github.com/user-attachments/assets/0786d9a7-ca10-4d1a-9bb6-250c3bfe82d2)

Framegen on:
![ffxvi_demo_2024_08_22_20_13_26_019](https://github.com/user-attachments/assets/033da02f-788f-4ed7-97fa-859f41d9204e)

**Comment by Lyall** [comment]
Actually, disregard my previous post. Frame generation (at least DLSS frame gen) is disable during certain cutscenes. Using SpecialK, I enabled the DLSS-G indicator and checked before and after entering a cutscene.

Before:
![fg on gameplay](https://github.com/user-attachments/assets/b23f4cfa-8df0-4e6b-895c-4572eb37f047)

After:
![frame gen cutsecne](https://github.com/user-attachments/assets/ceca7078-4192-4a76-af68-757d6faaaa2e)

**Comment by TryHard-twt** [comment]
I was going to test this mod when I get home, but is there still a problem with Framegen during cutscenes when using the mod? Do we all use Special K to fix it?

**Comment by Lyall** [comment]
> I was going to test this mod when I get home, but is there still a problem with Framegen during cutscenes when using the mod? Do we all use Special K to fix it?

I think you might be misunderstanding, I'm only mentioned SpecialK as it will let you enable an indicator that shows when DLSS Frame Generation is active. That's how I can tell for sure it's turning off in certain cutscenes.

**Comment by TryHard-twt** [comment]
> > I was going to test this mod when I get home, but is there still a problem with Framegen during cutscenes when using the mod? Do we all use Special K to fix it?
> 
> I think you might be misunderstanding, I'm only mentioning SpecialK as it will let you enable an indicator that shows when DLSS Frame Generation is active. That's how I can tell for sure it's turning off in certain cutscenes.

Ah, okay. Yes, I misunderstood. As for the mod itself, I'm only 20min in but it's working perfectly. :)

**Comment by Lyall** [comment]
![ffxvi_demo_2024_08_23_12_47_22_425](https://github.com/user-attachments/assets/807d041d-a563-444a-9e94-5f806345e145)

Alright, looks like I've found a way to leave frame generation on in cutscenes. Will need to do a bit more testing then hopefully I can implement it.

**Comment by Lyall** [comment]
Here is a test build with the option to force frame gen on all the time. Check `FFXVIFix.ini` to enable it and let me know if you run into any issues.

[FFXVIFix_v0.7.2_test2.zip](https://github.com/user-attachments/files/16729187/FFXVIFix_v0.7.2_test2.zip)

**Comment by TryHard-twt** [comment]
> Here is a test build with the option to force frame gen on all the time. Check `FFXVIFix.ini` to enable it and let me know if you run into any issues.
> 
> [FFXVIFix_v0.7.2_test2.zip](https://github.com/user-attachments/files/16729187/FFXVIFix_v0.7.2_test2.zip)

Much appreciated. 👍 I'll have to check it later on today but I'll see if it works as soon as possible.

**Comment by Karf** [comment]
This appears to be working for me, even for FMVs. It's trying to frame gen those, and it's producing something that looks like 35-42fps with some inconsistent frame rate/times, but that's fine. Nothings perfect, this is mod. For some reason, it's taking 95-99% of my 4090 to do it, but again, who cares. It's the game's code doing something weird there. If I limit the game to 30fps with framegen on, the FMV takes 45% of the GPU.

**Comment by Lyall** [comment]
> This appears to be working for me, even for FMVs. It's trying to frame gen those, and it's producing something that looks like 35-42fps with some inconsistent frame rate/times, but that's fine. Nothings perfect, this is mod. For some reason, it's taking 95-99% of my 4090 to do it, but again, who cares. It's the game's code doing something weird there. If I limit the game to 30fps with framegen on, the FMV takes 45% of the GPU.

This fits pretty much with what I was getting on my end too. Ideally it would maintain behaviour from the standard game. It turns off frame gen in cutscenes, pre-rendered videos and menus. I already have a hook for resizing videos so I can tell when one is playing. That would at least solve frame generation being on during video sequences.

**Comment by Lyall** [comment]
Alright, looking deeper I was able to find the function specifically responsible for turning off frame-gen in real time cutscenes. Here is another test build with that implemented.

[FFXVIFix_v0.7.2_test3.zip](https://github.com/user-attachments/files/16734221/FFXVIFix_v0.7.2_test3.zip)

**Comment by TryHard-twt** [comment]
Just came here to say it seems to be working perfectly now. Cutscenes on my end are just as smooth as the gameplay. 👍

**Comment by Karf** [comment]
Yeah, I can also confirm that v0.7.2_test3 is working perfectly. Framegen is no longer trying to muck up FMVs and is working during rendered cutscenes 👍

**Comment by Lyall** [comment]
Added in v0.7.2
