### ISSUE TITLE
Mod is on nexus and accepting donation

### ISSUE THREAD

**Issue by LittleTale** [Lyall/FFXVIFix#42]
Just wanted to be extra sure you were ok or knew that your fix is up on Nexus and the person seems to be using yourt pictures as his icon !
also ppl are donating to him.
found it strange that the picture of your avatar is lowres.
I just hope it's you or you are aware of it !

![image](https://github.com/user-attachments/assets/27576bcd-70b4-4ffa-9337-7e712d3ad9cd)
![image](https://github.com/user-attachments/assets/f0241ee5-be71-4e68-a3fd-ed86be7eaf70)

**Comment by Lyall** [comment]
I appreciate the concern, that's me though! You can see it's the same username I use on Patreon. I've started uploading stuff on Nexus Mods so that I can make sure they're kept up to date.

**Comment by LittleTale** [comment]
> I appreciate the concern, that's me though! You can see it's the same username I use on Patreon. I've started uploading stuff on Nexus Mods so that I can make sure they're kept up to date.

OH !!! ok ! 😅
I got a little overzealous thinking someone took your Mod for for granted and thrived on the responses like a lot of your other Mods uploaded on Nexus.
My bad !

**Comment by Lyall** [comment]
No worries, I'll close this issue now.
