### ISSUE TITLE
Mod suddenly not working

### ISSUE THREAD

**Issue by LongEggEater** [Lyall/FFXVIFix#43]
Mod was entirely functional, went to change some of my settings and the game became extremely laggy, restarted and the game is no longer ultrawide on menus or gameplay. 
Have tried reinstalling the fix, installing newer versions, and verifying game integrity all to no avail.
Not sure what else to try other than a full reinstall.
[FFXVIFix.log](https://github.com/user-attachments/files/17056405/FFXVIFix.log)

**Comment by Lyall** [comment]
Your log look good, though it says you're running at 2560x1440 so I'm not surprised ultrawide isn't working. Can you try changing to borderless/fullscreen?

**Comment by LongEggEater** [comment]
That fixed it, thanks
