### ISSUE TITLE
Feature request: A fix for the FPS halfing after swapping Eikons

### ISSUE THREAD

**Issue by intopuddles** [Lyall/FFXVIFix#44]
This is probably a long shot, but at this point we're at the mercy of Square to maybe fix this, because nearly everything you can imagine has been tried and there is no way around it other than restarting the game.

You can read about the issue a little more in [this](https://www.reddit.com/r/FFXVI/comments/1fkimer/bug_are_you_noticing_your_fps_suddenly_tank_out/) Reddit thread, but the gist is that swapping your Eikons will eventually cause your FPS to instantly (not progressively) tank. This seems to happen regardless of mods, GPU + CPU combinations, or graphics settings. This was not an issue in the demo, and seemingly only happens sometime post-Garuda. Some here may have noticed their FPS instantly tank, seemingly at random (occasionally when leaving cutscenes or menus), and never going back to normal.

Assuming you're affected, you can replicate the issue 100% of the time. **Simply boot/restart your game, go somewhere like the open world and switch Eikons a few times, and then just stand there and wait 2-5min**. If you triggered the bug, you will see your FPS and GPU usage instantly cut in half (at least). My 120fps turns into sub-60, almost like a forced vsync or disabling of framegen. However, for those experiencing this issue, it doesn't matter what settings or mods you enable/disable, as many players on Steam threads, Reddit, Discord and elsewhere have only now discovered this after a few hours of gameplay, and no solution of the dozens hypothesized have solved it.

As I said, this is probably a long shot for a feature, but the fact that this Eikon-switching trigger instantly cuts your FPS down in the manner that it does makes me think that it's something that might be able to be solved.

**Comment by Clapster34** [comment]
I have just discovered this same issue, restarting the game is the only fix I have found. It is pretty annoying.

**Comment by intopuddles** [comment]
UPDATE: A fix was found that I can confirm worked for me. Essentially you need to enable the Chroma app for FFXVI in Razer Synapse.

**Comment by Clapster34** [comment]
> UPDATE: A fix was found that I can confirm worked for me. Essentially you need to enable the Chroma app for FFXVI in Razer Synapse. I had previously disabled it.

Let me try this, thank you for looking into it!

**Comment by infinia-yzl** [comment]
> UPDATE: A fix was found that I can confirm worked for me. Essentially you need to enable the Chroma app for FFXVI in Razer Synapse. I had previously disabled it.

Can confirm that this worked for me! I must have replayed Garuda 6 times trying to solve this issue.

**Comment by Clapster34** [comment]
> > UPDATE: A fix was found that I can confirm worked for me. Essentially you need to enable the Chroma app for FFXVI in Razer Synapse. I had previously disabled it.
> 
> Let me try this, thank you for looking into it!

yup, worked for me as well, thanks again.

**Comment by Lyall** [comment]
Since this issue has a fix that's been identified and it's not related to FFXVIFix, I'll close this issue.
