### ISSUE TITLE
Cutscene Frame Generation readability fix

### ISSUE THREAD

**Issue by salemxvii** [Lyall/FFXVIFix#45]
Please consider updating the description of the Cutscene Frame Generation fix.

- Original: **"Set "Enabled" to true to stop frame generation from being disabled during real-time cutscenes"**

- Suggested: **"Set "Enabled" to true to enable frame generation during real-time cutscenes."**

This may be a less precise explanation, but avoids the potentially confusing double-negative.

**Comment by Lyall** [comment]
Added an updated description in v0.7.9.
