### ISSUE TITLE
Added option to lock cursor to game window -additional request

### ISSUE THREAD

**Issue by kyo-shi-ro** [Lyall/FFXVIFix#46]
is it possible to have this for borderless mode as well. i notice it only works for window mode and full screen. i have duel monitor so when im move my mouse to high up it goes to the next monitor. just a thought.  thanks

**Comment by Lyall** [comment]
The cursor is still not locked in borderless? I wasn't able to test it properly on my end since I don't have a second display. There's some calls to ClipCursor() that might be causing this. Would you be up for testing out a build with a potential fix?

**Comment by kyo-shi-ro** [comment]
Yes i can test it. just let me know what to do. just a heads up. i have no knowledge of coding or anything.

**Comment by Lyall** [comment]
Okay here you go. Just extract this over the files already in the game folder. You'll have to edit `FFXVIFix.ini` to enable the cursor lock feature.

[FFXVIFix_v0.7.9_test.zip](https://github.com/user-attachments/files/17065479/FFXVIFix_v0.7.9_test.zip)

This build stops two calls to ClipCursor(), so we'll see if that fixes it.

**Comment by kyo-shi-ro** [comment]
nice, that worked. i did have to change it to window mode then back to borderless mode in the game setting to make it work. nothing too big to worry about.

**Comment by Lyall** [comment]
Since we're killing two calls to ClipCursor(), do you mind testing one more build, just to confirm which one is responsible?

[FFXVIFix_v0.7.9_test2.zip](https://github.com/user-attachments/files/17065759/FFXVIFix_v0.7.9_test2.zip)

**Comment by kyo-shi-ro** [comment]
Test 2 failed. cursor still went to 2nd monitor in borderless. when doing the same thing as test 1.

**Comment by Lyall** [comment]
Alright perfect thanks for that. Here's (hopefully) a final build for you try.

[FFXVIFix_v0.7.9_test3.zip](https://github.com/user-attachments/files/17066012/FFXVIFix_v0.7.9_test3.zip)

**Comment by kyo-shi-ro** [comment]
ok, it works but this time. to active it. you need to tab out of the game then tab back into the game. good thing is. i didnt have to switch back to window mode and then back to borderless mode in game setting.

**Comment by Lyall** [comment]
Okay this build should work. At least it does in my testing, the cursor is locked to the window even in borderless and without having to alt+tab or anything else.

[FFXVIFix_v0.7.9_test4.zip](https://github.com/user-attachments/files/17067675/FFXVIFix_v0.7.9_test4.zip)

**Comment by kyo-shi-ro** [comment]
Perfect, this works. thank you so much.

**Comment by Lyall** [comment]
Added in v0.7.9
