### ISSUE TITLE
Disabling depth of field isn't working in current version

### ISSUE THREAD

**Issue by jw6642** [Lyall/FFXVIFix#47]
Downloaded the latest version of the fix and testing in the opening talking to Joshua or your father the Depth Of Field is still on even though I have set to enabled to true for DOF.

**Comment by Lyall** [comment]
Can you show a screenshot of it? I'm past that point in the game but I was able to replicate the previous depth of field bug.

**Comment by jw6642** [comment]
Sure.  I ran into some weird behavior other wise in the game after it happened so I am:

*Removing and reinstalling my nvidia graphics driver
*reinstalling the game and the fix

I'll test after that and get a screenshot.

**Comment by jw6642** [comment]
![20240919234853_1](https://github.com/user-attachments/assets/60a8e860-68af-41c0-a162-4ceeb8e697c3)
![20240919234911_1](https://github.com/user-attachments/assets/01694954-5235-4fee-8039-0ba94f9fdb33)

So this is what I was seeing.  However after updating to 0.7.9 the issue is fixed.  I'll keep this open in case you need to review anything on my end.  If not go ahead and close this.

Thank you for the amazing work you have done with this!
