### ISSUE TITLE
Hud Not scaling properly

### ISSUE THREAD

**Issue by BoyBumbo** [Lyall/FFXVIFix#49]
As you can se the top bar there isn't scaling quite right to the top of the screen when in 4:3 mode. (What I play in) 
![image](https://github.com/user-attachments/assets/32325e12-6b93-4c7d-87eb-345524fd2f8c)

**Comment by BoyBumbo** [comment]
BTW i am on windows 10 its just a reskin of windows 10. What I'm refering to is the tabs not correctly being at the top of the screen.

**Comment by Lyall** [comment]
Unfortunately those parts of the HUD cannot be spanned so you're always going to be left with a vertical gap at <16:9 and a horizontal gap >16:9.

**Comment by BoyBumbo** [comment]
Sounds good!
