### ISSUE TITLE
Anisotropic filtering

### ISSUE THREAD

**Issue by Lyram1** [Lyall/FFXVIFix#5]
Can you add a option for AF? I think ingame it uses only 2x or 4x AF . I have a AMD GPU and can't force it in the Driver.

**Comment by Lyall** [comment]
Haven't had much luck looking into this. Did some testing with forcing NVCP AF though to see if I could gauge the AF level.

High settings (application-controlled):
![high settings ingame](https://github.com/user-attachments/assets/874cf93c-8683-4dd8-9f55-63be917278e8)

x1 AF NVCP
![af off](https://github.com/user-attachments/assets/7d95d77c-990c-43f0-9f8f-0c9b20c6a7fe)

x4 AF NVCP
![af 4](https://github.com/user-attachments/assets/b525b7e2-bf92-45a5-a769-9bb58786d4af)

x16 AF NVCP
![af 16](https://github.com/user-attachments/assets/8ead6629-494f-44e0-8e9d-2253e8379d4d)

**Comment by Lyall** [comment]
Okay after wrestling with the game to get it to capture with NSight I think the game is using x8 AF (at least at high settings). Looking through the calls to CreateSampler() I can see anisotropy values ranging from 1-8. 

![image](https://github.com/user-attachments/assets/fd539f41-f649-4577-b9b9-4826bd51998b)

**Comment by Lyram1** [comment]
Hi, it looks like my bios has caused a bug in the game. I started the game earlier and it suddenly looked completely different. My framerate also increased by about 30% after the bios update.

**Comment by Lyram1** [comment]
before:
![Screenshot 2024-09-21 190501](https://github.com/user-attachments/assets/51c6ce42-5c83-49c2-b868-53fa6c1508b0)

**Comment by Lyram1** [comment]
before:
![Screenshot 2024-09-21 190501](https://github.com/user-attachments/assets/ce852cbf-403d-46cd-a635-29c5c217df2b)

**Comment by Lyram1** [comment]
after:
<img width="451" alt="Screenshot 2024-09-21 204315" src="https://github.com/user-attachments/assets/019dc253-e366-492b-a011-05cced85ff09">

**Comment by Holly-Chan** [comment]
> Hi, it looks like my bios has caused a bug in the game. I started the game earlier and it suddenly looked completely different, after I updated my bios. My framerate also increased by about 30% after the bios update.

Sorry to reply, but can you elaborate on that a bit? You updated your bios, as in, your motherboard's bios, and that fixed the issue? Or did you mean your gpu drivers? 
I'm asking because it seems weird to me that a motherboard bios would fix something like this.

**Comment by Lyram1** [comment]
It was my Gigabyte motherboard that caused the error.
It also seemed a bit strange to me that a BIOS update could solve such a problem or, to be more specific, that an old BIOS could cause such problems.
