### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Go2v** [Lyall/FFXVIFix#50]
Trojan detected on file: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XVI\FFXVIFix.asi

Trojan:Win32/Wacatac.B!ml

**Comment by Lyall** [comment]
It's a false positive, as detailed in #27 and #25. You can allow it in your anti-virus software and then redownload.

**Comment by Go2v** [comment]
Ok, thank you very much for your work, you really saved the game with your responsiveness to enable the ultrawide, thank you very much!
