### ISSUE TITLE
DoF still partially active

### ISSUE THREAD

**Issue by Kurochi51** [Lyall/FFXVIFix#58]
This might entirely be some other source of blurring, but it seems like objects really close to the camera still get dof applied to them. Here's some shots from the beginning of the game.
[Example1](https://i.imgur.com/lcgSH1L.jpeg) [Example2](https://i.imgur.com/S1zGdDB.png)

I was curious to see if the new address that fixed the npc dialogue was the cause, but that doesn't seem to be the case as I manually went in and tested if either or both worked, and it didn't.

**Comment by Lyall** [comment]
Can you try this test build? It seems to work on my end but it'd be good to confirm.

[FFXVIFix_v0.8.0_test.zip](https://github.com/user-attachments/files/17084581/FFXVIFix_v0.8.0_test.zip)

Before:
![ffxvi_2024_09_21_16_21_26_075](https://github.com/user-attachments/assets/f6a64955-1a03-4353-8591-96a0df8da232)

After:
![ffxvi_2024_09_21_16_21_16_191](https://github.com/user-attachments/assets/7024188b-b511-4c32-89b3-8ab1d3fcdeca)

**Comment by Kurochi51** [comment]
Seems to work fine

**Comment by cuong17hcb** [comment]
Thanks you very much @Lyall , this test build of you have also fixed the blurring outline around characters during cutscenes, I can finally use DLSS now instead DLAA and save lots of performance.
