### ISSUE TITLE
Unlocked cutscene FPS doesn't really correspond to actual frame rate increase

### ISSUE THREAD

**Issue by suyash691** [Lyall/FFXVIFix#6]
Even though the fps counter reads the unlocked value the visual appearance of the cutscenes appears to be 30 fps only

**Comment by Lyall** [comment]
Are you using frame generation?

**Comment by suyash691** [comment]
Not using framegen

**Comment by suyash691** [comment]
Not sure what is cause there. Maybe could be a composite cutscene which they talked about in gdc where they add pre-rendered stuff to dynamically rendered scene (ex-> the opening battle scene between two armies with shiva and titan)

**Comment by Drahsid** [comment]
Various cutscenes are prerendered with a very high bitrate. The videos for these cutscenes are 30 fps.

**Comment by AL2009man** [comment]
That being said; is it possible to also include the ability to select a framerate cap for cutscenes specifically? Something like this;

> [Cutscene Framerate]
> ; Select Framerate for Cutscenes or Photo Mode (default: 60)
> CutsceneFramerate = 60

the reason is that the Dynamic Resolution system seems to be based on the targeted in-game framerate, so having a better way to adjust that would be nice. Not only that; it's similar to how Gears 5 approaches its Cinematic framerate cap while giving PC players the option to either set a specific cap or disable it completely.

**Comment by Lyall** [comment]
> Not sure what is cause there. Maybe could be due to it being a composite cutscene which they talked about in gdc where they add pre-rendered stuff to dynamically rendered scene (ex-> the opening battle scene between two armies with shiva and titan)

You're likely just seeing pre-rendered video as mentioned by Drahsid. 

> That being said; is it possible to also include the ability to select a framerate cap for cutscenes specifically? Something like this;
> 
> > [Cutscene Framerate]
> > ; Select Framerate for Cutscenes or Photo Mode (default: 60)
> > CutsceneFramerate = 60
> 
> the reason is that the Dynamic Resolution system seems to be based on the targeted in-game framerate. Ideally; prioritizing visual fidelity in cutscene would help-- knowing how demanding the cutscenes can be on low-spec/mid-spec PCs and Steam Deck.
> 
> Not only that; it's similar to how Gears 5 approaches its Cinematic framerate cap while giving PC players the option to either set a specific cap or disable it completely.
> 
> edit: and a perfect excuse to run cutscenes at 48fps while making a IMAX-style Aspect ratio for the true cinematic experience. :P

I'd be somewhat hesitant about adding that as an option given most in-game frame limiters tend to be awful. The utility, however, of a per cutscene framerate limit might offset that though. Especially for lower end devices/PCs. I'll look into it and see if I can add it.

**Comment by Lyall** [comment]
Added in v0.7.7
