### ISSUE TITLE
Need Custom fps option for only hud/menu 

### ISSUE THREAD

**Issue by Monnigkeit** [Lyall/FFXVIFix#62]
I play the game at 30 fps with Frame gen I have nice 60 fps but the Ui and the menu are still at 30 frames is it possible that you can give us the option to set custom frames for the Ui/Menu

**Comment by Lyall** [comment]
It's not really recommended that you have frame generation running in menus. It's off by default for a reason. I won't be adding this to FFXVIFix.

**Comment by Monnigkeit** [comment]
Oh I see alright but is there like an Option where i can set my framerate only For the Menu and HUD without Frame gen For example i set only the Game to 30 fps and only the Menu and Ui to 60 fps
