### ISSUE TITLE
[Request] DLSS + AMD Frame Generation

### ISSUE THREAD

**Issue by ViniRust** [Lyall/FFXVIFix#65]
I know it's probably not on this mod scope, but since there's no one doing it, and this is the best and most complex mod for this game so far, I might as well ask here: develop a way to use DLSS upscaling/anti aliasing with AMD Frame Generation. 

It seems they've fixed DLSS implementation on released game, but unlike God of War Ragnarok, you can't use it with AMD Frame Generation, and FSR3 seems to be worst on released game than on the DEMO version.

**Comment by hawk16zz** [comment]
Adding on to Nukem's mod OMompm linked to: You can download the Universal edition and use the asi loader version and it will enable DLSS with FSR3 FrameGen, I'm using it right now

**Comment by ViniRust** [comment]
Thank you, guys, didn't knew there was an universal tool for t hat. Much appreciated!
