### ISSUE TITLE
Access is denied error when saving/finishing battle

### ISSUE THREAD

**Issue by nychitman1** [Lyall/FFXVIFix#66]
Upon finishing a battle or attempting a save, a pop-up indicating "Access is denied" will appear. In the latter scenario, it prevents the end user from saving their game entirely.

![2024-09-23 09_26_13-FINAL FANTASY XVI](https://github.com/user-attachments/assets/11061cb6-505a-47b1-b39e-274e3c43de51)

**Comment by Lyall** [comment]
This is a game issue, not related to FFXVIFix. One workaround is turning off "Controlled folder access" in "Virus & threat protection"->"Ransomware protection".
