### ISSUE TITLE
No Longer Able To Move Mouse Cursor To 2nd Monitor

### ISSUE THREAD

**Issue by RAWZeroG** [Lyall/FFXVIFix#68]
9/22/24
I play with a Dual Sense controller for this game on PC

0.7.9 was the last update where you were able to move your mouse cursor over to your monitor.

Updated to 0.8.1 and can no longer move mouse cursor.

I switched to borderless, hit windows key and was able to move it over. Switch it back to fullscreen and no issues. Mouse cursor stayed on 2nd monitor while I gamed on primary monitor with Dual Sense.

*UPDATE - 9/23/24
Today same thing happened again, repeated same solution, HOWEVER, as soon as I start playing with controller, mouse cursor is moved back to primary monitor.

**Comment by Lyall** [comment]
Set "LockCursor = false" in `FFXVIFix.ini`. It's enabled by default so that borderless mouse behaviour matches windowed.

**Comment by RAWZeroG** [comment]
@Lyall How silly of me not to think, I appreciate you and thank you so much!
