### ISSUE TITLE
Using ultrawide, borders displayed during movies are distractive

### ISSUE THREAD

**Issue by fguillotpro** [Lyall/FFXVIFix#7]
I'm not sure if you can do anything about it, but asking just in case.
When a movie cutscene is played, ultrawide fix obviously can't do anything but the remaining bars on both sides display random stuff often very bright (especially on HDR displays). I found it very distractive, it breaks the immersion. I was wondering if it could be forced to black somehow.
Thank you for your amazing work.

**Comment by fuzzbyte** [comment]
Here's an example of what I think OP is talking about. 
![Untitled](https://github.com/user-attachments/assets/88ebe81b-81da-4a51-94ea-0dd51178ec2f)

**Comment by fuzzbyte** [comment]
![Untitled](https://github.com/user-attachments/assets/47c128f9-b44d-42e0-ab73-0cbc765591ae)
Interestingly non FMV cutscenes still have some vignetting.

**Comment by fguillotpro** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/8451031/362704928-47c128f9-b44d-42e0-ab73-0cbc765591ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDU0MTMsIm5iZiI6MTcyNTAwNTExMywicGF0aCI6Ii84NDUxMDMxLzM2MjcwNDkyOC00N2MxMjhmOS1iNDRkLTQyZTAtYWI3My0wY2JjNzY1NTkxYWUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDgwNTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGY4ODlkYmE2ZGU0MTA4ZjViMGQyNGY1MjM3YWIyNzU0YzcyYTQzZGQ5ZDU5MDVkNTgwYmIyOTVjNDg0NjAzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CeHtD0K9leRhy7Wh4Vgg2L5qskSItSGfv35myOg60TY) Interestingly non FMV cutscenes still have some vignetting, even with vignettes disabled in the in-game graphics settings. Personally, this doesn't bother me much.

Yes the level of disturbance varies from "ok" to "ouch my eyes". Believe me your first example on OLED with HDR will kill your eyes :)

Anyway, I have seen on author's ko-fi page that he/she had a look at it at some point but said it's tricky/impossible.

**Comment by TimNedvyga** [comment]
@Lyall any update on this one?

**Comment by nlikeflynn** [comment]
Yes this is super distracting and annoying. Breaks immersion and flashbangs you at the same time lol. @Lyall please let us know if a fix is feasible. Thank you!

**Comment by nlikeflynn** [comment]
I found this line in the GBFRelink Fix thread. The loading, fades bit tipped me off as that is when this issue is happening in FF16. I think this is what is needed but I'm ignorant lol:

*Spanned HUD backgrounds to fill screen (loading, fades, etc)

**Comment by FakeGiraffe93** [comment]
is it possible to detect when a pre-rendered cutscene is playing and disable the UW fix during them? even done manually as a keybind

**Comment by FakeGiraffe93** [comment]
What about an option to have the pre rendered scenes fill instead? On my 21:9, I'd rather have the top n bottom cut out for the odd scene

**Comment by Lyall** [comment]
> What about an option to have the pre rendered scenes fill instead? On my 21:9, I'd rather have the top n bottom cut out for the odd scene

Cropping is an option I could add, though it's one I'd generally avoid due to the loss of information. 

One approach I could take is resizing the texture itself, instead of the display area, but this produces results like this:
![ffxvi_2024_09_18_23_53_15_615](https://github.com/user-attachments/assets/3a3c28d1-20e7-47a1-b643-a8776b76c09f)

Frankly I think that's about the same or worse than before but it could be an option.

One approach I want to look at is, if you start the game fresh with a new game, the first movie displays with a black background. If you carry on and get to a point where you can quit, if you start a new game again, that same movie plays without a black background. I'm wondering perhaps if there is something there that can be controlled to make sure a black background is visible.

**Comment by FakeGiraffe93** [comment]
That screenshot would be better. Some of the cutscenes like the one when you first get to lostwing for example, are very dark but has a bright white background. My aw3423dwf just tanks the brightness on the cutscene to adjust for all the white on the screen.

**Comment by mihir-io** [comment]
@FakeGiraffe93 I think it looks better in this screenshot, but I could see it being even worse than the current way in cases where the cutscene is bright and has a lot of motion.

If there's no way to toggle the aspect ratio to 16:9 before a cutscene starts, maybe there's a way to have ReShade put a black overlay behind the cutscene?

**Comment by DAOWAce** [comment]
Yeah this is extremely jarring.  We either get stretched cutscenes or properly cropped and bright horizon game world visible cutscenes.  Weird hearing that new game black screen changing thing.

Hope a good solution is found soon.  No flashbang, no weird stretched animated(?) texture like in vertical mobile videos, no cropping.  Just a simple black screen like many games do for their 16:9 cutscenes, be it a forced texture or just auto-toggling the aspect ratio fix.

Boggles my mind how Yoshida talked about Ultrawide in a Q&A then the demo, and now the official game, still no ultrawide support.  Massive black mark, especially when FF14 and FF15/Forspoken had full Ultrawide support.

**Comment by Lyall** [comment]
Alright I think I've made some progress with this. 

Before:
https://github.com/user-attachments/assets/e93c9ba6-ce32-40bf-a39f-897da917eba7

After:
https://github.com/user-attachments/assets/9af2f013-a773-466b-8839-917d9e34148d

**Comment by Lyall** [comment]
You can try out a test build with this change here:

https://github.com/Lyall/FFXVIFix/releases/download/v0.8.1/FFXVIFix_v0.8.1.zip

If you try it, let me know how it goes for you as this was quite tricky to solve and may cause issues that I haven't encountered yet.

**Comment by Night13x** [comment]
I just ran the beta update through the ropes....and I think you fixed it!

I started a new game - ran through about 30 minutes. All pre-render movie scenes had black borders vs the weird stuff that was happening prior. Also loaded up my save and hit the next pre-rendered. Same positive results.

Alienware OLED 34" ultrawide
3440 x 1440 resolution

**Comment by shauns2007** [comment]
I tried it on my Samsung G9 49"

The pre rendered scene in the beginning where you see the armies fighting always had the weird stuff for me, it's now fixed! The only thing I noticed, just putting it here was the transition just before you play as young Clive had some weird stuff.

@Lyall I thank you - I have been holding off playing till this was sorted.

**Comment by Lyall** [comment]
> I tried it on my Samsung G9 49"
> 
> The pre rendered scene in the beginning where you see the armies fighting always had the weird stuff for me, it's now fixed! The only thing I noticed, just putting it here, was the transition just before you play as young Clive had some weird stuff.
> 
> @Lyall I thank you - I have been holding off playing till this was sorted.

Thanks for testing. Are you able to elaborate on the "weird stuff"? Curious to hear what it was.

**Comment by shauns2007** [comment]
![image](https://github.com/user-attachments/assets/79f3e546-de82-4790-b1a0-9e18d888f97d)

Here's a screenshot, it doesn't last long at all though.

[Video](https://drive.google.com/file/d/1YHpAjG5_lLZjbS9XEmQE8IWt4kJdO9aD/view?usp=drive_link)

**Comment by Lyall** [comment]
That's great thanks for posting that. It seems like that's a leftover UI bug and fortunately not related to the fix for movies. 

https://github.com/user-attachments/assets/8237ecbc-c7e1-4cb2-9dc5-f64d6420f697

It still happens with the movie fix disabled. I will look into seeing if I can fix it. There are a few fades like that, that don't span the screen so it would be nice to fix them.

**Comment by shauns2007** [comment]
Legend, thank you!

I will happily test when you find something.

**Comment by nlikeflynn** [comment]
> ![image](https://private-user-images.githubusercontent.com/10954105/369682796-79f3e546-de82-4790-b1a0-9e18d888f97d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTQ4NTcsIm5iZiI6MTcyNzA1NDU1NywicGF0aCI6Ii8xMDk1NDEwNS8zNjk2ODI3OTYtNzlmM2U1NDYtZGU4Mi00NzkwLWIxYTAtOWUxOGQ4ODhmOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDAxMjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZWFmOWEwMjI3NDZmZmRkOGFkMmZkODdkMTk1MGMzYmQyMTgyMDg4NDkyYjkxNWE5NzMwMDVjYjJhZTJmYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.26TkBLS_RoDkNH_J2N8MwvV478MyyhLPMdc3T1dgkFw)
> 
> Here's a screenshot, it doesn't last long at all though.
> 
> [Video](https://drive.google.com/file/d/1YHpAjG5_lLZjbS9XEmQE8IWt4kJdO9aD/view?usp=drive_link)

This might need a separate issue opened then. Because it’s really distracting and it happens constantly. The movie pillarboxing appears fixed though and it looks great. Thank you!

**Comment by DAOWAce** [comment]
Ah.. was trying to test and didn't see the v8 release removed demo support.

RIP, I guess.  Never even got to the combat tutorial in the demo because of all the PC issues..

Still, thank you for working on these fixes; PC gaming on an ultrawide would be so much worse without people like you.

**Comment by Lyall** [comment]
> Ah.. was trying to test and didn't see the v8 release removed demo support.
> 
> RIP, I guess. Never even got to the combat tutorial in the demo because of all the PC issues..
> 
> Still, thank you for working on these fixes; PC gaming on an ultrawide would be so much worse without people like you.

Apologies for that, it's been under pretty rapid development and a few of the new features I added couldn't be easily ported back to the demo. It's a fair bit of extra work to check and maintain two different versions for parts of the fix so I ended up dropping support. 

> This might need a separate issue opened then. Because it’s really distracting and it happens constantly. The movie pillarboxing appears fixed though and it looks great. Thank you!

https://github.com/user-attachments/assets/331e7a55-cff7-476f-a2a5-3eab211ac2cc

Should be fixed in the next version.

**Comment by Lyall** [comment]
Alright with the remaining fades fixed and the bug from #64 fixed in v0.8.2, I can now close this issue.

**Comment by shauns2007** [comment]
@Lyall Absolute legend Sir, many thanks
