### ISSUE TITLE
mod doesnt work on my end

### ISSUE THREAD

**Issue by kipiLive** [Lyall/FFXVIFix#9]
i tried exporting the files on my 
C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XVI DEMO
still doesnt work. i even move the content of FFXVIFix-0.7.2 folder still doesnt work
tried with FFXVIFix-0.7.2 folder and FFXVIFix-0.7.2's content on same location still doesnt work

even the 30fps lock cut scene doesnt work.
tried changing my resolutions to something else, monitor hz, super resolutions, window mode still the same

my resolution is 3440x1440 (21:9)

**Comment by kipiLive** [comment]
tried 0.7.1 version it seems working somehow just the 0.72

**Comment by Lyall** [comment]
Please post a screenshot of the your game folder contents. Also please post your `FFXVIFix.log` file if you have one.

**Comment by Lyall** [comment]
Closing stale issue.
