### ISSUE TITLE
Game doesn't change to 3440 x 1440

### ISSUE THREAD

**Issue by xConfusion** [Lyall/FFXVIFix#90]
Hello, 

so I installed the fix and I can "change" the screen resolution to 3440 x 1440 but it won't change anything. 
I have black boarders on the side as if it's on 16:9. 

I tried to reinstall the mod and changed the resolution in the file to 3440 x 1440 but that won't help. 

How can I fix this issue?

**Comment by Lyall** [comment]
Can you post your `FFXVIFix.log` file please?

**Comment by xConfusion** [comment]
[FFXVIFix.log](https://github.com/user-attachments/files/17179075/FFXVIFix.log)

Of course. It should be attached.

**Comment by kawo** [comment]
Seems like you are trying with the demo.
Demo support was removed with 0.8x versions, last fix for demo version was [0.7.9](https://github.com/Lyall/FFXVIFix/releases/tag/v0.7.9).
May be that'll help mitigate your issue!

**Comment by Lyall** [comment]
Yep, as @kawo said, demo support was dropped past v0.7.9.
