### ISSUE TITLE
Frame Generation appears to be used in real-time cutscenes even when the INI option is set to false

### ISSUE THREAD

**Issue by jwittlincohen** [Lyall/FFXVIFix#95]
I have the following settings set in FFXVIFix.ini:

[Remove 30FPS Cap]
Enabled = true
Framerate = 29.97

[Cutscene Frame Generation]
Enabled = false

In game, I have DLSS Frame generation enabled with an in-game FPS target of 60 FPS.  I have SpecialK enforce a 120 FPS cap to maintain better frametimes.  This works great in gameplay but I noticed ghosting with FG in real-time cutscenes, so I changed the cutscene FG option from true to false.  However, real-time cutscenes are still rendering at 120 FPS per the RTSS overlay and SpecialK.  Oddly, a handful of cutscenes do appear to be rendering at 60 FPS, with the expected drop in GPU utilization.  Unlike the pre-rendered videos, these scenes do not have obvious aliasing and they do not seem particularly intensive graphically.  So, it seems the majority of real-time cutscenes are being rendered at 120 FPS with frame generation while a small subset are rendering at 60 FPS without FG.

**Comment by Lyall** [comment]
Do you have the cutscene frame generation option enabled in SpecialK? It has the same cutscene framerate stuff as FFXVIFix.

**Comment by jwittlincohen** [comment]
Yes, I did.  I didn't realize SpecialK also had fixes for FF16 specifically.  Should I disable any of the other options in SpecialK to avoid conflicts?

**Comment by Lyall** [comment]
> Yes, I did, unintentionally. I didn't realize SpecialK also had fixes for FF16 specifically. Should I disable any of the other options in SpecialK to avoid conflicts?

No there's nothing you need to adjust really. The maker of SpecialK has actually contributed to this fix as well so compatibility should be good. Any conflicting stuff will just fail and let the other software take precedence, like if the framerate stuff was already changed by SpecialK then the pattern scan would fail and move on in FFXVIFix.

**Comment by jwittlincohen** [comment]
It turns out that my issue was not SpecialK's cutscene feature.  Even with it disabled, cut scenes continued to be displayed at 120 FPS.  However, when I change the FF16Fix settings to not unlock the 30 FPS cap for cut scenes, I can confirm that cut scenes display at 30 FPS in SpecialK with its cut scene option disabled.  With the cut scene option enabled in SpecialK only, cut scenes run at 60 FPS.   As such, it appears that SpecialK does not actually enable frame generation for cut scenes.  In contrast, FF16Fix appears to be enabling FG for cutscenes regardless of the FG setting in the FFXVIFix.ini.

The following settings allow uncapped cutscenes without FG:

[Remove 30FPS Cap]
; Set "Enabled" to true to disable 30FPS cap in cutscenes/photo mode.
; Alternatively, set "Enabled" to false and enter a desired framerate to limit cutscene framerate.
; Remember that this framerate value is set before frame generation so set half of your desired framerate if using cutscene frame generation.
Enabled = false
Framerate = 29.97

[Cutscene Frame Generation]
; Set "Enabled" to true to permit frame generation during real-time cutscenes.
Enabled = false

SpecialK cutscene option enabled.
